version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: install-deps
          command: |
            pip install -r pip_requirements.txt
      - run:
          name: Test
          command: |
            python src/env_test.py
workflows:
  main:
    jobs:
      - build-and-test
