version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker: 
      - image: mongo:4.2.0
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          name: install-deps
          command: |
            pip install -r pip_requirements.txt
      - run:
          name: install-rust
          command: |
            sudo apt install cargo
      - run:
          name: build-rust
          command: |
            cd rusteval
            cargo build --release
      - python/save-cache
      - run:
          name: test-kuhn
          command: |
            cd kuhn
            python -m unittest
      - run:
          name: test-poker-env
          command: |
            cd poker
            python -m unittest
workflows:
  main:
    jobs:
      - build-and-test
