flatdeck:
  network_one:
    hidden_dims: [320,256]
    hand_dims: [128,128]
    board_dims: [192,192]
  network_two:
    hidden_dims: [128,128]
    hand_dims: [128,64]
    board_dims: [192,64]
smalldeck:
  network_one:
