flatdeck:
  network_one:
    hidden_dims: [256,256]
    hand_dims: [32,128]
    board_dims: [48,128]
    emb_size: 16
smalldeck:
  network_one:
    tblock: false
    attention: false
    identity: false
    num_heads: 4
    depth: 1
    wide: false
    output_dims: [30720,512]
    hidden_dims: [256,256]
    hand_dims: [32,128]
    board_dims: [48,128]
    emb_size: 16
  network_two:
    tblock: false
    attention: true
    identity: true
    num_heads: 4
    depth: 1
    wide: true
    output_dims: [30720,512]
    hidden_dims: [256,256]
    hand_dims: [32,128]
    board_dims: [48,128]
    emb_size: 16
  network_three:
    tblock: false
    attention: false
    identity: true
    num_heads: 4
    depth: 1
    wide: true
    output_dims: [30720,512]
    hidden_dims: [256,256]
    hand_dims: [32,128]
    board_dims: [48,128]
    emb_size: 16