flatdeck:
  network_one:
    hidden_dims: [256,256]
    hand_dims: [32,128]
    board_dims: [48,128]
    emb_size: 16
smalldeck:
  network_two:
    tblock: false
    attention: false
    identity: false
    num_heads: 4
    depth: 1
    wide: true
    hidden_dims: [256,256]
    hand_dims: [32,128]
    board_dims: [48,128]
    hand_stack_dims: [7680,512]
    board_stack_dims: [7680,512]
    emb_size: 16
    hand_emb_dims: [64,256]
    board_emb_dims: [80,128]
    output_dims: [15360,1024]