flatdeck:
  network_one:
    hidden_dims: [512,512]
    hand_dims: [128,256]
    board_dims: [192,256]
  network_two:
    hidden_dims: [512,256]
    hand_dims: [128,256]
    board_dims: [192,256]
smalldeck:
  network_one:
