flatdeck:
  network_one:
    hidden_dims: [256,256]
    hand_dims: [64,128]
    board_dims: [96,128]
    emb_size: 32
  network_two:
    hidden_dims: [256,128]
    hand_dims: [48,128]
    board_dims: [72,128]
    emb_size: 24
smalldeck:
  network_one:
    num_heads: 8
    depth: 2
    wide: true
    output_dims: [15360,512,256]
  network_two:
    num_heads: 4
    depth: 1
    wide: true
    output_dims: [15360,512]