flatdeck:
  network_one:
    hidden_dims: [256,256]
    hand_dims: [32,128]
    board_dims: [48,128]
    emb_size: 16
smalldeck:
  network_two:
    tblock: false
    attention: true
    identity: true
    num_heads: 4
    depth: 1
    wide: true
    output_dims: [1024,512,512]
    hidden_dims: [256,256]
    hand_dims: [32,128]
    board_dims: [48,128]
    hand_stack_dims: [7680,512]
    board_stack_dims: [7680,512]
    emb_size: 16